#!/usr/bin/env ruby
# frozen_string_literal: true

require "open3"
require_relative "learning_inventory"

LOCKED_COMMIT = "d7370df0170763e8a8a0db4542a1a181372b8895"
OUTPUT_PATH = File.expand_path("sync-only-manifest.tsv", __dir__)

def command_output(*command)
  output = IO.popen(command, &:read)
  abort "command failed: #{command.join(' ')}" unless $?.success?
  output
end

def read_locked_blobs(blob_ids)
  contents = {}
  Open3.popen3("git", "cat-file", "--batch") do |stdin, stdout, stderr, wait_thread|
    writer = Thread.new do
      blob_ids.each_value { |blob_id| stdin.puts(blob_id) }
      stdin.close
    end

    blob_ids.each do |path, expected_blob_id|
      header = stdout.gets
      abort "git cat-file ended before #{path}" if header.nil?

      blob_id, object_type, size_text = header.split
      unless blob_id == expected_blob_id && object_type == "blob"
        abort "expected blob #{expected_blob_id} for #{path}, got #{header.inspect}"
      end

      contents[path] = stdout.read(Integer(size_text, 10))
      abort "missing git cat-file separator after #{path}" unless stdout.read(1) == "\n"
    end

    writer.join
    error_output = stderr.read
    abort "git cat-file failed: #{error_output}" unless wait_thread.value.success?
  end
  contents
end

repository_root = File.expand_path("..", __dir__)
Dir.chdir(repository_root)

entries = command_output("git", "ls-tree", "-r", LOCKED_COMMIT).lines.to_h do |line|
  match = line.chomp.match(/\A(\d+) \w+ ([0-9a-f]+)\t(.+)\z/)
  abort "unexpected git ls-tree output: #{line.inspect}" if match.nil?

  [match[3], [match[1], match[2]]]
end
contents = read_locked_blobs(entries.transform_values(&:last))
learning_set = LearningInventory.learning_paths(entries.transform_values(&:first), contents).to_h do |path|
  [path, true]
end

rows = entries.each_with_object([]) do |(path, (mode, _blob_id)), result|
  content = contents.fetch(path)
  next if learning_set[path]

  action, reason = LearningInventory.sync_disposition(path, content, mode: mode)
  result << [action, path, reason].join("\t")
end

manifest = <<~HEADER + rows.join("\n") + "\n"
  # Generated by tasks/generate-sync-manifest.rb from #{LOCKED_COMMIT}.
  # action<TAB>repository path<TAB>mandatory copy rule or concrete exclusion reason
HEADER

if ARGV == ["--check"]
  abort "#{OUTPUT_PATH} is stale; run ruby tasks/generate-sync-manifest.rb" unless File.file?(OUTPUT_PATH) && File.binread(OUTPUT_PATH) == manifest

  puts "OK: #{rows.length} sync-only blobs match #{OUTPUT_PATH}"
elsif ARGV.empty?
  File.binwrite(OUTPUT_PATH, manifest)
  puts "Wrote #{rows.length} sync-only blobs to #{OUTPUT_PATH}"
else
  abort "usage: ruby tasks/generate-sync-manifest.rb [--check]"
end
